---
title: "CASE 4 - Teaching"
author: Liam Phan, Michael Bigler, Tania Loureiro, William Elkiess, Dakota Cuellar
  and Ilyana El Mendili
date: "2023-03-10"
output: 
  rmdformats::downcute:
    code_folding: hide
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, warning = FALSE,comment = FALSE, error = FALSE,options(scipen=999))
rm(list = ls())

```

# Packages

```{r packages}
library(knitr) # html tables
library(gtsummary)
```

# Data Loading

```{r data loading}
teaching <- readxl::read_excel('Bteaching.xls')
teaching <- data.frame(teaching)
teaching$GROUP <- factor(teaching$GROUP, level = c('C', 'E'), labels = c('Control', 'Experiment'))
teaching$GENDER <- factor(teaching$GENDER, level = c('M', 'F'), labels =  c('Male', 'Female'))
teaching$PREF <- factor(teaching$PREF, level = c('A', 'N', 'T', 'K', 'V'), labels = c('A', 'N', 'T', 'K', 'V')) # get understandable lables
teaching$SLEVEL <- factor(teaching$SLEVEL, level = c('E', 'H'), labels = c('Elementary', 'Highschool'))
```

# Data exploratory

```{r exploratory}
kable(summary(teaching))
```

```{r}
teaching$index = 1:nrow(teaching)
tsibble::tsibble(teaching, index = index)

table1 <- tbl_summary(
  teaching,
  by = GROUP, # split table by group
  missing = "no" # don't list missing data separately
) |> 
  add_n() |>  # add column with total number of non-missing observations
  add_p() |>  # test for a difference between groups
  modify_header(label = "**Variable**") |> # update the column header
  bold_labels() 
table1
```

```{r}
tbl_strata <-
  teaching |> 
  tbl_strata(
    strata = GROUP,
    .tbl_fun =
      ~ .x |>
        tbl_summary(by = SESSION, missing = "no") |>
      add_n() |>  # add column with total number of non-missing observations
      add_p() |>  # test for a difference between groups
      modify_header(label = "**Variable**") |> # update the column header
      bold_labels() ,
    .header = "**{strata}**, N = {n}"
  )
tbl_strata
```

## Dummy encoding

```{r}
library(fastDummies)
teaching <- dummy_columns(teaching, select_columns = c('GROUP', 'SESSION', 'PREF', 'GENDER', 'SLEVEL'), remove_selected_columns = TRUE, remove_first_dummy = TRUE)
```

```{r}
library(dplyr)
teaching$DIFF <- teaching$POST - teaching$PRE
mod <- lm(DIFF ~ ., data = subset(teaching, select = -c(PRE, POST)))
summary(mod)
plot(mod)


source(file="RFn_Plot-lmSim.R")
plot.lmSim(mod)
```

I guess we can assume normality as qqplot in bootstrap.

```{r}
library(regclass)
VIF(mod)
```

Shows which variables have higher importance

```{r}
s <- step(mod, direction = 'backward')
s
mod2 <- lm(DIFF ~ ATT + GROUP_Experiment + SESSION_S2 + PREF_N + PREF_K + PREF_V, subset(teaching, select = -c(PRE, POST)))

summary(mod2)
```

Selects the best model backwards which makes some variables significant. 

Now a model which would make sense

```{r}
# model due to sense
mod3 <- lm(DIFF ~ ATT + GROUP_Experiment + PREF_N + PREF_K + 
    PREF_V + PREF_T, subset(teaching, select = -c(PRE, POST)))

summary(mod3)
```



# References {.unnumbered}

[gtsummary](https://www.danieldsjoberg.com/gtsummary/)

[Stratified gtsummary tables](https://www.danieldsjoberg.com/gtsummary/reference/tbl_strata.html)
